#!/bin/sh

# Copyright (c) 2020, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of Intel Corporation nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# generate json metric files in perf tree from TMAM
# gen-metrics TMEM-file linux-tree


PATH=$PATH:.

TMAM=$1
LINUX=$2

set -e
set -x

gen() {
	extract-tmam-metrics.py $1 $TMAM > x.json
	merge-json x.json cstate.json > $LINUX/tools/perf/pmu-events/arch/x86/$2
}

# XXX update
gen SKL/KBL skylake/skl-metrics.json
gen CLX cascadelakex/clx-metrics.json
gen SKX skylakex/skx-metrics.json
gen BDX broadwellx/bdx-metrics.json
gen BDW/BDW-DE broadwell/bdw-metrics.json
gen HSX haswellx/hsx-metrics.json
gen HSW haswell/hsw-metrics.json
gen IVT ivytown/ivt-metrics.json
gen IVB ivybridge/ivb-metrics.json
gen JKT/SNB-EP jaketown/jkt-metrics.json
gen SNB sandybridge/snb-metrics.json
